In [16]:
# import required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Step 1: Load Prepared Dataset

In [17]:
#load clean and preprocesssed data
fitness_data = pd.read_excel("Fitness Classes Data/Cleaned_Preprocessed_Dataset_Yogeshwar Tribhuvan.xlsx")

### Step 2: Dataset Overview

In [18]:
fitness_data.head()

,ActivitySiteID,ActivityDescription,BookingEndDate,BookingStartTime,MaxBookees,Number Booked,Price (INR)
0,HXP,20-20-20 2.45pm-3.45pm,2018-04-08,1900-01-01 14:45:00,25,12,499
1,HXP,20-20-20 2.45pm-3.45pm,2018-04-15,1900-01-01 14:45:00,25,15,499
2,HXP,20-20-20 2.45pm-3.45pm,2018-04-22,1900-01-01 14:45:00,25,14,499
3,HXP,20-20-20 2.45pm-3.45pm,2018-04-29,1900-01-01 14:45:00,25,9,499
4,HXP,20-20-20 2.45pm-3.45pm,2018-05-06,1900-01-01 14:45:00,25,7,499

In [19]:
fitness_data.tail()

,ActivitySiteID,ActivityDescription,BookingEndDate,BookingStartTime,MaxBookees,Number Booked,Price (INR)
3284,TSC,Zumba 6.30-7.30pm,2018-06-18,1900-01-01 18:30:00,18,9,1299
3285,TSC,Zumba 6.30-7.30pm,2018-06-25,1900-01-01 18:30:00,18,9,1299
3286,TSC,Zumba - 6-7pm,2018-06-07,1900-01-01 18:00:00,50,16,1299
3287,TSC,Zumba - 6-7pm,2018-06-14,1900-01-01 18:00:00,50,13,1299
3288,TSC,Zumba - 6-7pm,2018-06-21,1900-01-01 18:00:00,50,12,1299

In [20]:
fitness_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 3289 entries, 0 to 3288
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ActivitySiteID       3289 non-null   str
 1   ActivityDescription  3289 non-null   str
 2   BookingEndDate       3289 non-null   datetime64[us]
 3   BookingStartTime     3289 non-null   datetime64[us]
 4   MaxBookees           3289 non-null   int64
 5   Number Booked        3289 non-null   int64
 6   Price (INR)          3289 non-null   int64
dtypes: datetime64[us](2), int64(3), str(2)
memory usage: 258.3 KB

In [22]:
#display the number of rows and columns
fitness_data.shape

(3289, 7)