## High Demand Class and Time Identification

### Import necessary library

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Load the Dataset

In [2]:
fitness_data = pd.read_excel("Cleaned_Preprocessed_Dataset_Yogeshwar Tribhuvan.xlsx")

### Dataset Information

In [3]:
fitness_data.info()
fitness_data.head()

<class 'pandas.DataFrame'>
RangeIndex: 3289 entries, 0 to 3288
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ActivitySiteID       3289 non-null   str
 1   ActivityDescription  3289 non-null   str
 2   BookingEndDate       3289 non-null   datetime64[us]
 3   BookingStartTime     3289 non-null   datetime64[us]
 4   MaxBookees           3289 non-null   int64
 5   Number Booked        3289 non-null   int64
 6   Price (INR)          3289 non-null   int64
dtypes: datetime64[us](2), int64(3), str(2)
memory usage: 258.3 KB

,ActivitySiteID,ActivityDescription,BookingEndDate,BookingStartTime,MaxBookees,Number Booked,Price (INR)
0,HXP,20-20-20 2.45pm-3.45pm,2018-04-08,1900-01-01 14:45:00,25,12,499
1,HXP,20-20-20 2.45pm-3.45pm,2018-04-15,1900-01-01 14:45:00,25,15,499
2,HXP,20-20-20 2.45pm-3.45pm,2018-04-22,1900-01-01 14:45:00,25,14,499
3,HXP,20-20-20 2.45pm-3.45pm,2018-04-29,1900-01-01 14:45:00,25,9,499
4,HXP,20-20-20 2.45pm-3.45pm,2018-05-06,1900-01-01 14:45:00,25,7,499

### Data Preparation

In [4]:
fitness_data["BookingEndDate"] = pd.to_datetime(fitness_data["BookingEndDate"])

fitness_data["DayName"] = fitness_data["BookingEndDate"].dt.day_name()

fitness_data["Month"] = fitness_data["BookingEndDate"].dt.month_name()

fitness_data["Hour"] = pd.to_datetime(
    fitness_data["BookingStartTime"].astype(str)
).dt.hour

In [5]:
def session(hour):
    if hour < 12:
        return "Morning"
    elif hour < 17:
        return "Afternoon"
    else:
        return "Evening"

fitness_data["Session"] = fitness_data["Hour"].apply(session)

### High Demand Classes

In [6]:
class_demand = (
    fitness_data.groupby("ActivityDescription")["Number Booked"]
    .sum()
    .sort_values(ascending=False)
)

class_demand

ActivityDescription
Body Combat 7.00-8.00pm      1031
Aquafit 7.00-8.00pm           915
Pilates 1.45-2.45pm           730
Line Dance 10.45-11.45am      673
Body Con 10.30-11.30am        611
                             ...
Junior Gym10-11am 8-13yrs       1
Junior Gym 4-5pm 8-13yrs        1
B L T- Weight Manage Clas       1
B L T Antenatal Mums            1
Wm Better Living Team           1
Name: Number Booked, Length: 280, dtype: int64

### High Demand Locations

In [7]:
location_demand = (
    fitness_data.groupby("ActivitySiteID")["Number Booked"]
    .sum()
    .sort_values(ascending=False)
)

location_demand

ActivitySiteID
BRP    14068
HXP    12391
SBP    12297
NBL    10793
TSC     6656
Name: Number Booked, dtype: int64

### High Demand Days

In [8]:
day_demand = (
    fitness_data.groupby("DayName")["Number Booked"]
    .sum()
    .sort_values(ascending=False)
)

day_demand

DayName
Tuesday      12097
Wednesday    10737
Monday        9253
Thursday      8777
Friday        7294
Saturday      4766
Sunday        3281
Name: Number Booked, dtype: int64

### High Demand Sessions

In [9]:
session_demand = (
    fitness_data.groupby("Session")["Number Booked"]
    .sum()
    .sort_values(ascending=False)
)

session_demand

Session
Morning      24926
Evening      21886
Afternoon     9393
Name: Number Booked, dtype: int64

### Monthly Demand Analysis

In [10]:
month_demand = (
    fitness_data.groupby("Month")["Number Booked"]
    .sum()
    .sort_values(ascending=False)
)

month_demand

Month
April    19592
May      18855
June     17758
Name: Number Booked, dtype: int64

### Correlation Analysis

In [11]:
correlation = fitness_data[
    ["Price (INR)", "MaxBookees", "Number Booked"]
].corr()

correlation

               Price (INR)  MaxBookees  Number Booked
Price (INR)       1.000000   -0.093681      -0.188412
MaxBookees       -0.093681    1.000000       0.443628
Number Booked    -0.188412    0.443628       1.000000

In [14]:
import joblib
high_demand = {
    "Top Class": class_demand.idxmax(),
    "Top Location": location_demand.idxmax(),
    "Top Day": day_demand.idxmax(),
    "Top Session": session_demand.idxmax()
}

joblib.dump(high_demand, "high_demand.pkl")

print("High Demand insights saved!")

High Demand insights saved!